import { useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Calendar from "@/components/calendar";
import Details from "./Details";
import ToDoList from "@/components/toDoList";
import AddToDo from "@/components/addToDo";
import User from "@/components/user";

export default function Home() {
  const [showDetails, setShowDetails] = useState(false);
  const [data, setData] = useState(null);

  const showDetailsHandle = (dayStr) => {
    setData(dayStr);
    setShowDetails(true);
  };
  return (
    <>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <User />
        <Calendar showDetailsHandle={showDetailsHandle} />
        <br />
        {showDetails && <Details data={data} />}
        <ToDoList data={data} />
        <AddToDo />
      </main>
    </>
  );
}
