import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Modal from "@/components/modal";

export default function Home() {
  return (
    <>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Modal />
      </main>
    </>
  );
}
