import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import ToDoList from "@/components/toDoList";
import AddToDo from "@/components/addToDo";

export default function Home() {
  return (
    <>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AddToDo />
        <ToDoList />
      </main>
    </>
  );
}
